import os
import sys
import json
import subprocess
import glob
from datetime import datetime
import google.generativeai as genai

# Configure API Key
api_key = os.getenv("GOOGLE_API_KEY")
if not api_key:
    print("Error: GOOGLE_API_KEY not set.")
    sys.exit(1)

genai.configure(api_key=api_key)
model = genai.GenerativeModel('gemini-pro')

def read_file_safe(filename):
    """Safely read a file and return content, or empty string if not found."""
    try:
        if os.path.exists(filename):
            with open(filename, 'r', encoding='utf-8', errors='ignore') as f:
                return f.read()
    except Exception as e:
        print(f"Error reading {filename}: {e}")
    return ""

if __name__ == "__main__":
    target = os.getenv("TARGET_URL")
    if not target:
        if len(sys.argv) < 2:
            print("Usage: python ai_security_agent.py <target_url>")
            sys.exit(1)
        target = sys.argv[1]
    
    print(f"[+] Processing scan results for: {target}")
    
    # Read outputs from the workflow steps
    nmap_out = read_file_safe("nmap_results.txt")
    nuclei_out = read_file_safe("nuclei_results.txt")
    sqlmap_out = read_file_safe("sqlmap_results.txt")
    
    # Combine findings
    all_findings = f"""
    === NMAP RESULTS ===
    {nmap_out if nmap_out.strip() else "No ports scanned or no results."}
    
    === NUCLEI RESULTS ===
    {nuclei_out if nuclei_out.strip() else "No vulnerabilities found by Nuclei."}
    
    === SQLMAP RESULTS ===
    {sqlmap_out if sqlmap_out.strip() else "No SQL injection found or scan timed out."}
    """
    
    # Check if we have ANY data
    if not (nmap_out.strip() or nuclei_out.strip() or sqlmap_out.strip()):
        print("[+] No data found from any scanner. Generating 'All Clear' report.")
        report = f"""# Security Scan Report

**Target:** {target}
**Date:** {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Status:** ⚠️ **NO DATA**

## Executive Summary
The automated scanners (Nmap, Nuclei, SQLMap) did not produce any output. This could mean:
1. The target is unreachable.
2. The target blocked the scan (WAF/Firewall).
3. The scan timed out.

## Recommendation
Please verify the target URL and network connectivity. Try running the scan again.

---
*Generated by Hades-Sec-Bot*
"""
    else:
        print("[+] Sending combined findings to AI for analysis...")
        prompt = f"""
        You are a senior cybersecurity analyst and penetration tester.
        Analyze the following raw output from three security tools: Nmap, Nuclei, and SQLMap.
        
        RAW DATA:
        {all_findings}
        
        TASK:
        1. **Filter False Positives**: Ignore generic "info" messages or obvious false alarms. Focus on actionable vulnerabilities.
        2. **Correlate**: If Nmap shows port 80 open and Nuclei finds a vulnerability on port 80, link them.
        3. **Prioritize**: Rank findings by severity (Critical > High > Medium > Low).
        4. **Format**: Create a professional Markdown report with:
           - Executive Summary
           - Critical/High Findings (with Proof of Concept if available)
           - Medium/Low Findings
           - Remediation Steps
           - Conclusion
        
        If no vulnerabilities are found despite the scans, state that clearly as "No Vulnerabilities Detected".
        """
        
        try:
            response = model.generate_content(prompt)
            report = response.text
        except Exception as e:
            report = f"AI Analysis Failed: {str(e)}\n\nRaw Findings:\n{all_findings}"

    # Save Report
    safe_name = target.replace(":", "_").replace("/", "_").replace("\\", "_")
    timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
    filename = f"report_{safe_name}_{timestamp}.md"
    
    with open(filename, "w", encoding="utf-8") as f:
        f.write(report)
    
    print(f"[+] Report saved to: {filename}")
    print("\n[+] Process Complete.")
